-- Consolidated SQLite schema for the Zettelgarden backend.
--
-- Source: pg_dump --schema-only of the live dev Postgres DB, translated to
-- SQLite by schema/sqlite/translate.py (see migration design doc Phase 2).
--
-- This single file represents the *current final-state* schema. New installs
-- build the DB from this file (loaded via server/sqlsplit.go). The historical
-- Postgres migrations under schema/*.sql are retained only for the one-time
-- ETL (Phase 6b).
--
-- NOT here by design:
--   * CREATE FUNCTION / TRIGGER / COMMENT ON -- trigger logic is ported to Go
--     in Phase 5 (see design doc); nothing in Go reads the GIN indexes.
--   * The 3 GIN indexes (FTS to_tsvector on files.extracted_text, JSONB
--     containment on chat_messages.referenced_cards, array containment on
--     notifications.filter_tags) -- verified dead, dropped.
--   * Sequences -- replaced by INTEGER PRIMARY KEY AUTOINCREMENT.
--
-- Timestamp columns are declared DATETIME (not TEXT): modernc.org/sqlite needs
-- the declared type to return time.Time (migration design doc decision D5).
-- SQLite's loose affinity still stores the value as text either way.
--
-- Generated by translate.py; re-run it against a fresh dump to regenerate.
-- Do not hand-edit.

PRAGMA foreign_keys = ON;

CREATE TABLE admin_audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  admin_user_id INTEGER NOT NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id INTEGER,
  details TEXT DEFAULT '{}' NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  FOREIGN KEY (admin_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE agent_activity_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_id INTEGER,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id INTEGER,
  details TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (agent_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE api_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  last_used_at DATETIME,
  revoked_at DATETIME,
  is_active BOOLEAN DEFAULT true,
  description TEXT,
  CONSTRAINT revoked_at_required_when_inactive CHECK ((((is_active = 1) AND (revoked_at IS NULL)) OR ((is_active = 0) AND (revoked_at IS NOT NULL)))),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE audit_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  entity_id INTEGER NOT NULL,
  entity_type TEXT NOT NULL,
  action TEXT NOT NULL,
  details TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL
);

CREATE TABLE backlinks (
  source_id TEXT,
  target_id TEXT,
  created_at DATETIME,
  updated_at DATETIME,
  source_id_int INTEGER,
  target_id_int INTEGER
);

CREATE TABLE card_chunks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER,
  user_id INTEGER,
  chunk_text TEXT,
  chunk_id INTEGER,
  FOREIGN KEY (card_pk) REFERENCES cards(id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE card_embeddings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER,
  user_id INTEGER,
  chunk INTEGER,
  FOREIGN KEY (card_pk) REFERENCES cards(id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE card_tags (
  card_pk INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  PRIMARY KEY (card_pk, tag_id),
  FOREIGN KEY (card_pk) REFERENCES cards(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE card_templates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  name TEXT DEFAULT '' NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE card_views (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  user_id INTEGER,
  FOREIGN KEY (card_pk) REFERENCES cards(id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_id TEXT,
  title TEXT,
  body TEXT,
  is_reference INTEGER DEFAULT 0,
  link TEXT,
  created_at DATETIME,
  updated_at DATETIME,
  user_id INTEGER,
  is_deleted BOOLEAN DEFAULT false,
  parent_id INTEGER,
  is_literature_card BOOLEAN DEFAULT false,
  is_flashcard BOOLEAN DEFAULT false,
  flashcard_state TEXT,
  flashcard_reps INTEGER DEFAULT 0,
  flashcard_lapses INTEGER DEFAULT 0,
  flashcard_last_review DATETIME,
  flashcard_due DATETIME,
  flashcard_stability REAL DEFAULT 0,
  flashcard_difficulty REAL DEFAULT 0,
  card_schema_id INTEGER,
  structured_data TEXT,
  created_by_agent_id INTEGER,
  version INTEGER DEFAULT 1,
  sync_uuid TEXT,
  FOREIGN KEY (card_schema_id) REFERENCES schema_definitions(id),
  FOREIGN KEY (created_by_agent_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  name TEXT,
  description TEXT,
  regex TEXT,
  is_active BOOLEAN DEFAULT true,
  created_by INTEGER,
  updated_by INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE chat_conversations (
  id TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  user_id INTEGER NOT NULL,
  title TEXT,
  model TEXT DEFAULT 'gpt-4o-mini' NOT NULL,
  system_prompt TEXT,
  starred BOOLEAN DEFAULT false,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  primary_card_id INTEGER,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (primary_card_id) REFERENCES cards(id) ON DELETE SET NULL
);

CREATE TABLE chat_instructions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  instructions TEXT DEFAULT '',
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE chat_messages (
  id TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  conversation_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT,
  tool_calls TEXT,
  tool_call_id TEXT,
  sequence_number INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  referenced_cards TEXT,
  status TEXT DEFAULT 'completed' NOT NULL,
  CONSTRAINT chat_messages_role_check CHECK ((role IN ('user', 'assistant', 'system', 'tool'))),
  CONSTRAINT chat_messages_status_check CHECK ((status IN ('pending', 'processing', 'completed', 'failed'))),
  PRIMARY KEY (id),
  FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE
);

CREATE TABLE chat_tool_calls (
  id TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  user_id INTEGER NOT NULL,
  conversation_id TEXT,
  message_id TEXT,
  tool_name TEXT NOT NULL,
  tool_arguments TEXT,
  tool_result TEXT,
  execution_time_ms INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  PRIMARY KEY (id),
  FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE,
  FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE chat_usage_quotas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  quota_type TEXT NOT NULL,
  current_usage INTEGER DEFAULT 0,
  max_limit INTEGER NOT NULL,
  reset_date DATE DEFAULT CURRENT_DATE,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  CONSTRAINT chat_usage_quotas_quota_type_check CHECK ((quota_type IN ('messages_per_day', 'tool_calls_per_day', 'conversations_per_day'))),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE email_accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  email_address TEXT NOT NULL,
  jmap_server_url TEXT DEFAULT 'https://api.fastmail.com/jmap/session' NOT NULL,
  is_active BOOLEAN DEFAULT true,
  last_sync_at DATETIME,
  sync_status TEXT DEFAULT 'active',
  jmap_state TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  imap_server TEXT DEFAULT 'imap.fastmail.com:993',
  imap_server_type TEXT DEFAULT 'imap',
  imap_uid INTEGER,
  imap_uid_validity INTEGER,
  app_password_encrypted TEXT,
  CONSTRAINT email_accounts_sync_status_check CHECK ((sync_status IN ('active', 'syncing', 'error', 'disabled'))),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE email_attachments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  email_id INTEGER NOT NULL,
  file_id INTEGER,
  filename TEXT NOT NULL,
  content_type TEXT,
  size INTEGER,
  s3_key TEXT,
  thumbnail_path TEXT,
  content_id TEXT,
  is_inline BOOLEAN DEFAULT false,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE,
  FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE email_card_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email_id INTEGER NOT NULL,
  card_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE,
  FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);

CREATE TABLE email_fact_junction (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  email_id INTEGER NOT NULL,
  fact_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE,
  FOREIGN KEY (fact_id) REFERENCES facts(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE email_triage_decisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email_id INTEGER NOT NULL,
  decision TEXT NOT NULL,
  confidence REAL NOT NULL,
  reasoning TEXT,
  is_auto_executed BOOLEAN DEFAULT false,
  created_at DATETIME DEFAULT (datetime('now')),
  CONSTRAINT email_triage_decisions_confidence_check CHECK (((confidence >= (0)) AND (confidence <= (1)))),
  CONSTRAINT email_triage_decisions_decision_check CHECK ((decision IN ('archive', 'delete', 'keep', 'convert_to_card'))),
  FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);

CREATE TABLE emails (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  email_account_id INTEGER,
  message_id TEXT NOT NULL,
  thread_id TEXT,
  subject TEXT,
  from_address TEXT,
  from_name TEXT,
  to_addresses TEXT,
  body_text TEXT,
  body_html TEXT,
  received_at DATETIME,
  folder TEXT DEFAULT 'Inbox',
  status TEXT DEFAULT 'unprocessed',
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  imap_uid INTEGER,
  is_read BOOLEAN DEFAULT false,
  card_id INTEGER,
  CONSTRAINT emails_status_check CHECK ((status IN ('unprocessed', 'triaged', 'reviewed', 'archived', 'deleted', 'converted'))),
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE SET NULL,
  FOREIGN KEY (email_account_id) REFERENCES email_accounts(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE entities (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  name TEXT,
  description TEXT,
  type TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  card_pk INTEGER,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (card_pk) REFERENCES cards(id)
);

CREATE TABLE entity_card_junction (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  entity_id INTEGER,
  card_pk INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  chunk_id INTEGER,
  FOREIGN KEY (entity_id) REFERENCES entities(id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE entity_fact_junction (
  user_id INTEGER NOT NULL,
  entity_id INTEGER NOT NULL,
  fact_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE,
  FOREIGN KEY (fact_id) REFERENCES facts(id) ON DELETE CASCADE
);

CREATE TABLE external_calendars (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  sync_enabled BOOLEAN DEFAULT true,
  sync_interval_hours INTEGER DEFAULT 1,
  color TEXT DEFAULT '#6366f1',
  last_synced_at DATETIME,
  last_error TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  username TEXT,
  password TEXT,
  CONSTRAINT name_not_empty CHECK ((length(trim(name)) > 0)),
  CONSTRAINT sync_interval_hours_bounds CHECK (((sync_interval_hours >= 1) AND (sync_interval_hours <= 168))),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE external_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  external_calendar_id INTEGER,
  title TEXT NOT NULL,
  description TEXT,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  all_day BOOLEAN DEFAULT false,
  location TEXT,
  external_uid TEXT,
  external_url TEXT,
  recurrence_rule TEXT,
  color TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  last_synced_at DATETIME,
  card_pk INTEGER,
  recurrence_id TEXT,
  recurrence_instance INTEGER,
  FOREIGN KEY (card_pk) REFERENCES cards(id) ON DELETE SET NULL,
  FOREIGN KEY (external_calendar_id) REFERENCES external_calendars(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE fact_card_junction (
  fact_id INTEGER NOT NULL,
  card_pk INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  is_origin BOOLEAN DEFAULT false,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  PRIMARY KEY (fact_id, card_pk),
  FOREIGN KEY (card_pk) REFERENCES cards(id) ON DELETE CASCADE,
  FOREIGN KEY (fact_id) REFERENCES facts(id) ON DELETE CASCADE
);

CREATE TABLE facts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  card_pk INTEGER NOT NULL,
  fact TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  FOREIGN KEY (card_pk) REFERENCES cards(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE file_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT,
  type TEXT,
  path TEXT,
  filename TEXT,
  size INTEGER,
  created_by INTEGER,
  updated_by INTEGER,
  card_pk INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  is_deleted BOOLEAN DEFAULT false,
  user_id INTEGER,
  thumbnail_path TEXT,
  description TEXT,
  extracted_text TEXT,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE files_tags (
  file_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  PRIMARY KEY (file_id, tag_id),
  FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES file_tags(id) ON DELETE CASCADE
);

CREATE TABLE flashcard_reviews (
  id INTEGER,
  card_pk INTEGER,
  user_id INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  rating INTEGER,
  FOREIGN KEY (card_pk) REFERENCES cards(id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE inactive_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  card_updated_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL
);

CREATE TABLE keywords (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER,
  user_id INTEGER,
  keyword TEXT,
  FOREIGN KEY (card_pk) REFERENCES cards(id)
);

CREATE TABLE llm_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  job_type TEXT NOT NULL,
  status TEXT DEFAULT 'pending' NOT NULL,
  priority INTEGER DEFAULT 5 NOT NULL,
  payload TEXT NOT NULL,
  result TEXT,
  error_message TEXT,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  started_at DATETIME,
  completed_at DATETIME,
  retry_count INTEGER DEFAULT 0 NOT NULL,
  max_retries INTEGER DEFAULT 3 NOT NULL,
  timeout_seconds INTEGER DEFAULT 300 NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  last_heartbeat DATETIME,
  correlation_id TEXT,
  CONSTRAINT llm_jobs_status_check CHECK ((status IN ('pending', 'running', 'completed', 'failed', 'cancelled'))),
  CONSTRAINT llm_jobs_type_check CHECK ((job_type IN ('summarization', 'entity_extraction', 'fact_entity_extraction', 'chat', 'memory', 'email'))),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE llm_models (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  provider_id INTEGER,
  name TEXT NOT NULL,
  model_identifier TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (provider_id) REFERENCES llm_providers(id)
);

CREATE TABLE llm_providers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  base_url TEXT,
  api_key_required BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  user_id INTEGER,
  api_key TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE llm_query_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  model TEXT,
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  created_at DATETIME DEFAULT (datetime('now')),
  cost_usd NUMERIC,
  request_type TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notification_preferences (
  user_id INTEGER NOT NULL,
  show_unprocessed_emails BOOLEAN DEFAULT true,
  show_starred_articles BOOLEAN DEFAULT true,
  show_priority_tasks BOOLEAN DEFAULT true,
  show_priority_feeds BOOLEAN DEFAULT true,
  items_per_page INTEGER DEFAULT 50,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  CONSTRAINT notification_preferences_items_per_page_check CHECK (((items_per_page >= 10) AND (items_per_page <= 200))),
  PRIMARY KEY (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  source_type TEXT NOT NULL,
  source_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  preview TEXT,
  "timestamp" DATETIME NOT NULL,
  importance_score INTEGER DEFAULT 0,
  is_read BOOLEAN DEFAULT false,
  is_archived BOOLEAN DEFAULT false,
  filter_tags TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  CONSTRAINT notifications_importance_score_check CHECK ((importance_score >= 0)),
  CONSTRAINT notifications_source_type_check CHECK ((source_type IN ('email', 'rss', 'task'))),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE starred_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER,
  user_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  FOREIGN KEY (card_pk) REFERENCES cards(id) ON DELETE CASCADE
);

CREATE TABLE starred_searches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  search_term TEXT NOT NULL,
  search_config TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE revenue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  stripe_subscription_id TEXT NOT NULL,
  stripe_invoice_id TEXT NOT NULL,
  amount_cents INTEGER NOT NULL,
  currency TEXT DEFAULT 'usd' NOT NULL,
  description TEXT,
  payment_date DATETIME DEFAULT (datetime('now')),
  created_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE rss_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  feed_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  content TEXT,
  author TEXT,
  url TEXT NOT NULL,
  published_at DATETIME,
  fetched_at DATETIME DEFAULT (datetime('now')),
  read BOOLEAN DEFAULT false,
  card_id INTEGER,
  is_starred BOOLEAN DEFAULT false,
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE SET NULL,
  FOREIGN KEY (feed_id) REFERENCES rss_feeds(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE rss_feeds (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  url TEXT NOT NULL,
  name TEXT NOT NULL,
  folder TEXT,
  auto_tags TEXT DEFAULT '',
  fetch_interval INTEGER DEFAULT 60,
  last_fetched_at DATETIME,
  last_error TEXT,
  enabled BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  priority BOOLEAN DEFAULT false,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE rss_folders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE rss_seen_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  feed_id INTEGER NOT NULL,
  url TEXT NOT NULL,
  first_seen_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (feed_id) REFERENCES rss_feeds(id) ON DELETE CASCADE
);

CREATE TABLE scheduled_job_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_name TEXT NOT NULL,
  started_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  completed_at DATETIME,
  status TEXT NOT NULL,
  error_message TEXT,
  retry_count INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  CONSTRAINT scheduled_job_runs_status_check CHECK ((status IN ('running', 'completed', 'failed', 'cancelled')))
);

CREATE TABLE schema_definitions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  owner_id INTEGER NOT NULL,
  fields TEXT NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  is_deleted BOOLEAN DEFAULT false,
  slug TEXT,
  CONSTRAINT schema_definitions_name_check CHECK ((length(name) <= 255)),
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE spreadsheets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  card_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  rows INTEGER DEFAULT 5 NOT NULL,
  cols INTEGER DEFAULT 5 NOT NULL,
  data TEXT DEFAULT '{}' NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  FOREIGN KEY (card_id) REFERENCES cards(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE stripe_plans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stripe_product_id TEXT NOT NULL,
  stripe_price_id TEXT NOT NULL,
  name TEXT,
  description TEXT,
  active BOOLEAN NOT NULL,
  unit_amount INTEGER,
  currency TEXT,
  "interval" TEXT,
  interval_count INTEGER,
  trial_days INTEGER,
  metadata TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now'))
);

CREATE TABLE summarizations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  input_text TEXT NOT NULL,
  status TEXT DEFAULT 'pending' NOT NULL,
  result TEXT,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  card_pk INTEGER,
  prompt_tokens INTEGER DEFAULT 0,
  completion_tokens INTEGER DEFAULT 0,
  total_tokens INTEGER DEFAULT 0,
  cost REAL DEFAULT 0,
  model TEXT DEFAULT '',
  llm_job_id INTEGER,
  CONSTRAINT summarizations_status_check CHECK ((status IN ('pending', 'processing', 'complete', 'failed'))),
  FOREIGN KEY (card_pk) REFERENCES cards(id) ON DELETE CASCADE,
  FOREIGN KEY (llm_job_id) REFERENCES llm_jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  color TEXT,
  user_id INTEGER,
  is_deleted BOOLEAN DEFAULT false,
  created_at DATETIME,
  updated_at DATETIME,
  version INTEGER DEFAULT 1,
  sync_uuid TEXT
);

CREATE TABLE task_dependencies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id INTEGER NOT NULL,
  blocking_task_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  CONSTRAINT task_dependencies_check CHECK ((task_id <> blocking_task_id)),
  FOREIGN KEY (blocking_task_id) REFERENCES tasks(id) ON DELETE CASCADE,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE task_statuses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  color TEXT NOT NULL,
  icon TEXT,
  "position" INTEGER NOT NULL,
  is_default BOOLEAN DEFAULT false,
  is_complete_state BOOLEAN DEFAULT false,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE task_tags (
  task_pk INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  PRIMARY KEY (task_pk, tag_id),
  FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
  FOREIGN KEY (task_pk) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  card_pk INTEGER,
  user_id INTEGER NOT NULL,
  scheduled_date DATETIME,
  due_date DATETIME,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  completed_at DATETIME,
  title TEXT NOT NULL,
  is_complete BOOLEAN DEFAULT false NOT NULL,
  is_deleted BOOLEAN DEFAULT false NOT NULL,
  priority TEXT,
  status TEXT DEFAULT 'todo',
  reminder_time DATETIME,
  reminder_sent BOOLEAN DEFAULT false,
  description TEXT,
  external_uid TEXT,
  external_calendar_id INTEGER,
  parent_task_id INTEGER,
  sort_order INTEGER,
  version INTEGER DEFAULT 1,
  sync_uuid TEXT,
  FOREIGN KEY (external_calendar_id) REFERENCES external_calendars(id) ON DELETE SET NULL,
  FOREIGN KEY (parent_task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE unsorted_cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  body TEXT,
  created_at DATETIME,
  updated_at DATETIME
);

CREATE TABLE user_llm_configurations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER,
  model_id INTEGER,
  api_key TEXT,
  custom_settings TEXT DEFAULT '{}',
  is_default BOOLEAN DEFAULT false,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (model_id) REFERENCES llm_models(id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_memories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  memory TEXT,
  created_at DATETIME DEFAULT (datetime('now')),
  updated_at DATETIME DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_stats (
  user_id INTEGER NOT NULL,
  card_count INTEGER DEFAULT 0 NOT NULL,
  task_count INTEGER DEFAULT 0 NOT NULL,
  file_count INTEGER DEFAULT 0 NOT NULL,
  chat_message_count INTEGER DEFAULT 0 NOT NULL,
  llm_cost_usd NUMERIC DEFAULT 0.0000 NOT NULL,
  revenue_cents INTEGER DEFAULT 0 NOT NULL,
  updated_at DATETIME DEFAULT (datetime('now')) NOT NULL,
  PRIMARY KEY (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT,
  email TEXT,
  password TEXT,
  created_at DATETIME,
  updated_at DATETIME,
  is_admin BOOLEAN DEFAULT false NOT NULL,
  email_validated BOOLEAN DEFAULT false NOT NULL,
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  stripe_subscription_status TEXT,
  stripe_subscription_frequency TEXT,
  stripe_current_plan TEXT,
  last_login DATETIME,
  can_upload_files BOOLEAN DEFAULT true,
  max_file_storage INTEGER DEFAULT 100000000,
  dashboard_card_pk INTEGER DEFAULT 0,
  last_seen DATETIME,
  memory_has_changed BOOLEAN DEFAULT true,
  auth_provider TEXT DEFAULT 'local',
  github_id TEXT,
  has_seen_getting_started BOOLEAN DEFAULT false,
  stripe_cancel_at_period_end BOOLEAN DEFAULT false,
  timezone TEXT DEFAULT 'UTC',
  show_tasks BOOLEAN DEFAULT true,
  show_rss BOOLEAN DEFAULT true,
  last_memory_job_id INTEGER,
  caldav_url TEXT,
  caldav_token TEXT,
  is_agent BOOLEAN DEFAULT false NOT NULL,
  owner_user_id INTEGER,
  api_key_hash TEXT,
  oidc_provider TEXT,
  oidc_sub TEXT,
  CONSTRAINT check_agent_has_api_key CHECK (((NOT is_agent) OR (api_key_hash IS NOT NULL))),
  CONSTRAINT check_agent_not_admin CHECK ((NOT ((is_agent = 1) AND (is_admin = 1)))),
  FOREIGN KEY (last_memory_job_id) REFERENCES llm_jobs(id) ON DELETE SET NULL,
  FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
);


-- Ordinary indexes (btree -> SQLite; partial-index predicates translated)
CREATE INDEX idx_admin_audit_log_action ON admin_audit_log (action);
CREATE INDEX idx_admin_audit_log_admin_user_id ON admin_audit_log (admin_user_id);
CREATE INDEX idx_admin_audit_log_created_at ON admin_audit_log (created_at DESC);
CREATE INDEX idx_admin_audit_log_target ON admin_audit_log (target_type, target_id);
CREATE INDEX idx_agent_activity_action ON agent_activity_log (action);
CREATE INDEX idx_agent_activity_agent ON agent_activity_log (agent_id);
CREATE INDEX idx_agent_activity_created ON agent_activity_log (created_at DESC);
CREATE INDEX idx_api_keys_user_id ON api_keys (user_id);
CREATE INDEX idx_card_templates_user_id ON card_templates (user_id);
CREATE INDEX idx_cards_card_schema_id ON cards (card_schema_id);
CREATE INDEX idx_cards_created_by_agent ON cards (created_by_agent_id) WHERE (created_by_agent_id IS NOT NULL);
CREATE INDEX idx_cards_user_created ON cards (user_id, created_at) WHERE (is_deleted = 0);
CREATE INDEX idx_chat_conversations_primary_card_id ON chat_conversations (primary_card_id);
CREATE INDEX idx_chat_conversations_updated_at ON chat_conversations (updated_at DESC);
CREATE INDEX idx_chat_conversations_user_id ON chat_conversations (user_id);
CREATE INDEX idx_chat_instructions_user_id ON chat_instructions (user_id);
CREATE INDEX idx_chat_messages_conversation_id ON chat_messages (conversation_id);
CREATE INDEX idx_chat_messages_conversation_status ON chat_messages (conversation_id, status);
CREATE INDEX idx_chat_messages_sequence ON chat_messages (conversation_id, sequence_number);
CREATE INDEX idx_chat_messages_status ON chat_messages (status);
CREATE INDEX idx_chat_tool_calls_conversation_id ON chat_tool_calls (conversation_id);
CREATE INDEX idx_chat_tool_calls_user_id ON chat_tool_calls (user_id);
CREATE INDEX idx_chat_usage_quotas_user_reset ON chat_usage_quotas (user_id, reset_date);
CREATE INDEX idx_email_accounts_active_user ON email_accounts (user_id) WHERE (is_active = 1);
CREATE INDEX idx_email_accounts_is_active ON email_accounts (is_active);
CREATE INDEX idx_email_accounts_user_id ON email_accounts (user_id);
CREATE INDEX idx_email_attachments_email_id ON email_attachments (email_id);
CREATE INDEX idx_email_attachments_file_id ON email_attachments (file_id);
CREATE INDEX idx_email_attachments_inline ON email_attachments (email_id, is_inline);
CREATE INDEX idx_email_attachments_user_id ON email_attachments (user_id);
CREATE INDEX idx_email_card_links_card_id ON email_card_links (card_id);
CREATE INDEX idx_email_card_links_email_id ON email_card_links (email_id);
CREATE INDEX idx_email_fact_junction_email_id ON email_fact_junction (email_id);
CREATE INDEX idx_email_fact_junction_fact_id ON email_fact_junction (fact_id);
CREATE INDEX idx_email_fact_junction_user_id ON email_fact_junction (user_id);
CREATE INDEX idx_email_triage_decisions_email_id ON email_triage_decisions (email_id);
CREATE INDEX idx_emails_card_id ON emails (card_id);
CREATE INDEX idx_emails_imap_uid ON emails (imap_uid) WHERE (imap_uid IS NOT NULL);
CREATE INDEX idx_emails_received_at ON emails (received_at DESC);
CREATE INDEX idx_emails_user_account ON emails (user_id, email_account_id);
CREATE INDEX idx_emails_user_folder ON emails (user_id, folder);
CREATE INDEX idx_emails_user_is_read_status ON emails (user_id, is_read, status) WHERE ((is_read = 0) AND (status = 'unprocessed'));
CREATE INDEX idx_emails_user_status ON emails (user_id, status);
CREATE INDEX idx_external_calendars_user ON external_calendars (user_id);
CREATE INDEX idx_external_events_calendar ON external_events (external_calendar_id);
CREATE INDEX idx_external_events_card_pk ON external_events (card_pk);
CREATE INDEX idx_external_events_recurrence_id ON external_events (recurrence_id);
CREATE INDEX idx_external_events_recurrence_series ON external_events (user_id, recurrence_id);
CREATE INDEX idx_external_events_user_time ON external_events (user_id, start_time, end_time);
CREATE INDEX idx_file_tags_user_id ON file_tags (user_id);
CREATE INDEX idx_files_tags_file_id ON files_tags (file_id);
CREATE INDEX idx_files_tags_tag_id ON files_tags (tag_id);
CREATE INDEX idx_llm_jobs_correlation_id ON llm_jobs (correlation_id) WHERE (correlation_id IS NOT NULL);
CREATE INDEX idx_llm_jobs_created_at ON llm_jobs (created_at DESC);
CREATE INDEX idx_llm_jobs_priority ON llm_jobs (priority) WHERE ((status)= 'pending');
CREATE INDEX idx_llm_jobs_running_heartbeat ON llm_jobs (id, started_at, last_heartbeat) WHERE ((status)= 'running');
CREATE INDEX idx_llm_jobs_status ON llm_jobs (status) WHERE (status IN ('pending', 'running'));
CREATE INDEX idx_llm_jobs_updated_at ON llm_jobs (updated_at DESC);
CREATE INDEX idx_llm_jobs_user_status ON llm_jobs (user_id, status);
CREATE INDEX idx_notifications_user_timestamp ON notifications (user_id, "timestamp" DESC);
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, is_read, is_archived) WHERE ((is_read = 0) AND (is_archived = 0));
CREATE INDEX idx_rss_articles_card_id ON rss_articles (card_id);
CREATE INDEX idx_rss_articles_read ON rss_articles (user_id, read);
CREATE INDEX idx_rss_articles_starred ON rss_articles (user_id, is_starred);
CREATE INDEX idx_rss_articles_user_feed ON rss_articles (user_id, feed_id);
CREATE INDEX idx_rss_feeds_enabled ON rss_feeds (enabled);
CREATE INDEX idx_rss_feeds_user ON rss_feeds (user_id);
CREATE INDEX idx_rss_folders_user ON rss_folders (user_id);
CREATE INDEX idx_rss_seen_articles_feed_url ON rss_seen_articles (feed_id, url);
CREATE INDEX idx_scheduled_job_runs_created_at ON scheduled_job_runs (created_at);
CREATE INDEX idx_scheduled_job_runs_job_name ON scheduled_job_runs (job_name);
CREATE INDEX idx_scheduled_job_runs_started_at ON scheduled_job_runs (started_at DESC);
CREATE INDEX idx_scheduled_job_runs_status ON scheduled_job_runs (status);
CREATE INDEX idx_schema_definitions_owner_id ON schema_definitions (owner_id);
CREATE UNIQUE INDEX idx_schema_definitions_owner_name ON schema_definitions (owner_id, lower(trim(name))) WHERE (is_deleted = 0);
CREATE UNIQUE INDEX idx_schema_definitions_owner_slug ON schema_definitions (owner_id, slug);
CREATE INDEX idx_spreadsheets_card_id ON spreadsheets (card_id);
CREATE INDEX idx_spreadsheets_user_card ON spreadsheets (user_id, card_id);
CREATE INDEX idx_spreadsheets_user_id ON spreadsheets (user_id);
CREATE INDEX idx_summarizations_llm_job_id ON summarizations (llm_job_id);
CREATE INDEX idx_summarizations_user_card_created ON summarizations (user_id, card_pk, created_at DESC);
CREATE INDEX idx_summarizations_user_created ON summarizations (user_id, created_at DESC);
CREATE INDEX idx_task_dependencies_blocking_task_id ON task_dependencies (blocking_task_id);
CREATE INDEX idx_task_dependencies_task_id ON task_dependencies (task_id);
CREATE INDEX idx_task_statuses_position ON task_statuses (user_id, "position");
CREATE INDEX idx_task_statuses_user ON task_statuses (user_id);
CREATE INDEX idx_tasks_external_uid ON tasks (external_uid) WHERE (external_uid IS NOT NULL);
CREATE INDEX idx_tasks_parent_id ON tasks (parent_task_id);
CREATE INDEX idx_tasks_sort_order ON tasks (user_id, sort_order) WHERE (sort_order IS NOT NULL);
CREATE INDEX idx_tasks_status ON tasks (status);
CREATE INDEX idx_tasks_user_completed ON tasks (user_id, completed_at) WHERE ((is_deleted = 0) AND (completed_at IS NOT NULL));
CREATE INDEX idx_tasks_user_created ON tasks (user_id, created_at) WHERE (is_deleted = 0);
CREATE UNIQUE INDEX idx_unique_active_key_name_per_user ON api_keys (user_id, name) WHERE (is_active = 1);
CREATE INDEX idx_user_stats_card_count ON user_stats (card_count);
CREATE INDEX idx_user_stats_revenue ON user_stats (revenue_cents DESC);
CREATE INDEX idx_users_agent ON users (is_agent) WHERE (is_agent = 1);
CREATE INDEX idx_users_caldav_token ON users (caldav_token) WHERE (caldav_token IS NOT NULL);
CREATE INDEX idx_users_last_memory_job_id ON users (last_memory_job_id);
CREATE INDEX idx_users_owner ON users (owner_user_id) WHERE (is_agent = 1);
CREATE UNIQUE INDEX idx_users_oidc_sub ON users (oidc_provider, oidc_sub) WHERE (oidc_sub IS NOT NULL);
CREATE UNIQUE INDEX idx_users_email ON users (email);
CREATE INDEX starred_cards_user_id_idx ON starred_cards (user_id);
CREATE INDEX starred_searches_user_id_idx ON starred_searches (user_id);

-- Unique constraints (from ALTER TABLE ... ADD CONSTRAINT UNIQUE)
CREATE UNIQUE INDEX uq_chat_instructions_user_id ON chat_instructions (user_id);
CREATE UNIQUE INDEX uq_chat_messages_conversation_id_sequence_number ON chat_messages (conversation_id, sequence_number);
CREATE UNIQUE INDEX uq_chat_usage_quotas_user_id_quota_type_reset_date ON chat_usage_quotas (user_id, quota_type, reset_date);
CREATE UNIQUE INDEX uq_email_accounts_user_id_email_address ON email_accounts (user_id, email_address);
CREATE UNIQUE INDEX uq_email_card_links_email_id_card_id ON email_card_links (email_id, card_id);
CREATE UNIQUE INDEX uq_email_fact_junction_user_id_email_id_fact_id ON email_fact_junction (user_id, email_id, fact_id);
CREATE UNIQUE INDEX uq_emails_user_id_message_id ON emails (user_id, message_id);
CREATE UNIQUE INDEX uq_entities_user_id_name ON entities (user_id, name);
CREATE UNIQUE INDEX uq_entity_card_junction_entity_id_card_pk ON entity_card_junction (entity_id, card_pk);
CREATE UNIQUE INDEX uq_entity_fact_junction_entity_id_fact_id ON entity_fact_junction (entity_id, fact_id);
CREATE UNIQUE INDEX uq_external_calendars_user_id_url ON external_calendars (user_id, url);
CREATE UNIQUE INDEX uq_external_events_user_id_external_uid ON external_events (user_id, external_uid);
CREATE UNIQUE INDEX uq_llm_models_provider_id_model_identifier ON llm_models (provider_id, model_identifier);
CREATE UNIQUE INDEX uq_notifications_user_id_source_type_source_id ON notifications (user_id, source_type, source_id);
CREATE UNIQUE INDEX uq_starred_cards_card_pk_user_id ON starred_cards (card_pk, user_id);
CREATE UNIQUE INDEX uq_rss_articles_user_id_url ON rss_articles (user_id, url);
CREATE UNIQUE INDEX uq_rss_feeds_user_id_url ON rss_feeds (user_id, url);
CREATE UNIQUE INDEX uq_rss_folders_user_id_name ON rss_folders (user_id, name);
CREATE UNIQUE INDEX uq_rss_seen_articles_feed_id_url ON rss_seen_articles (feed_id, url);
CREATE UNIQUE INDEX uq_stripe_plans_stripe_price_id ON stripe_plans (stripe_price_id);
CREATE UNIQUE INDEX uq_task_dependencies_task_id_blocking_task_id ON task_dependencies (task_id, blocking_task_id);
CREATE UNIQUE INDEX uq_task_statuses_user_id_name ON task_statuses (user_id, name);
CREATE UNIQUE INDEX uq_task_statuses_user_id_position ON task_statuses (user_id, "position");
CREATE UNIQUE INDEX uq_file_tags_user_id_name ON file_tags (user_id, name);
CREATE UNIQUE INDEX uq_user_llm_configurations_user_id_model_id ON user_llm_configurations (user_id, model_id);
CREATE UNIQUE INDEX uq_user_memories_user_id ON user_memories (user_id);
CREATE UNIQUE INDEX uq_users_caldav_token ON users (caldav_token);

-- task_saved_searches: added by migration 0143-add-task-saved-searches.sql.
-- This table was missing from the 2026-07-25 pg_dump snapshot used to seed the
-- consolidated schema (the dev DB had not yet applied 0143); appended here in
-- Phase 6a so the suite sees the expected shape. Translate rules: SERIAL ->
-- INTEGER PRIMARY KEY AUTOINCREMENT, TIMESTAMPTZ -> DATETIME, NOW() ->
-- datetime('now'), COMMENT ON dropped.
CREATE TABLE IF NOT EXISTS task_saved_searches (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users (id),
  name TEXT NOT NULL,
  filter_string TEXT NOT NULL DEFAULT '',
  sort_field TEXT NOT NULL DEFAULT 'priority',
  sort_direction TEXT NOT NULL DEFAULT 'asc',
  view_mode TEXT NOT NULL DEFAULT 'list',
  created_at DATETIME NOT NULL DEFAULT (datetime('now')),
  updated_at DATETIME NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS task_saved_searches_user_id_idx ON task_saved_searches (user_id);

-- sync_log: append-only change feed for the local-first sync engine (epic
-- Zettelgarden-v5b, Phase 0a). Every mutation on the synced tables (cards,
-- tasks, tags) writes one row here in the same transaction as the mutation;
-- the sync API (Phase 0b) serves it as the incremental changes feed. The log
-- must never be pruned while any client cursor trails it.
CREATE TABLE sync_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  collection TEXT NOT NULL,
  row_uuid TEXT NOT NULL,
  op TEXT NOT NULL,
  version INTEGER NOT NULL,
  created_at DATETIME DEFAULT (datetime('now')) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sync_log_user_id ON sync_log (user_id, id);

-- sync_clients: per-device heartbeat for sync_log retention (v5b.5). Each
-- push reports the device's last-known local cursor; pruning never removes
-- rows any live client cursor trails.
CREATE TABLE sync_clients (
  user_id INTEGER NOT NULL,
  device_id TEXT NOT NULL,
  cursor INTEGER NOT NULL DEFAULT 0,
  last_seen_at DATETIME NOT NULL,
  PRIMARY KEY (user_id, device_id)
);

-- Sync identity uniqueness: sync_uuid is the immutable per-row identity used
-- by the sync engine (cards' id/card_id are both unsafe: id is server-assigned,
-- card_id is user-editable). Partial indexes so NULL (pre-backfill legacy rows
-- or test fixtures) is allowed; the Phase 0a self-heal backfills NULLs at boot.
CREATE UNIQUE INDEX IF NOT EXISTS idx_cards_sync_uuid ON cards (sync_uuid) WHERE sync_uuid IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_sync_uuid ON tasks (sync_uuid) WHERE sync_uuid IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_sync_uuid ON tags (sync_uuid) WHERE sync_uuid IS NOT NULL;
