/**
 * Builds shimSource.generated.js from webviewShimSource.js — the injected
 * WebView script as a string constant (see webviewShimSource.js for why
 * Function.prototype.toString cannot be used under Hermes).
 *
 * Run: node scripts/buildShimSource.js
 * Commit the generated file; rerun whenever webviewShimSource.js changes.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const SRC = path.join(__dirname, '..', 'webviewShimSource.js');
const OUT = path.join(__dirname, '..', 'shimSource.generated.js');

const source = fs.readFileSync(SRC, 'utf8');

const generated = [
  "'use strict';",
  '// GENERATED by scripts/buildShimSource.js — do not edit.',
  '// Source of truth: webviewShimSource.js',
  '/**',
  ' * Returns the JavaScript injected into the WebView before content loads.',
  ' * __ZG_PLATFORM__ is substituted with the actual platform at runtime.',
  ' */',
  'module.exports = function shimSource(platform) {',
  '  return ' +
    JSON.stringify(source) +
    '.replace(/__ZG_PLATFORM__/g, JSON.stringify(platform));',
  '};',
  '',
].join('\n');

fs.writeFileSync(OUT, generated);
console.log(
  `wrote ${OUT} (${generated.length} bytes, source ${source.length} bytes)`,
);
