// SigV4 request signing for the one-time B2→local storage migration.
//
// This deliberately implements AWS Signature Version 4 by hand (crypto/hmac +
// net/http only) so that cmd/migrate-storage has NO aws-sdk-go dependency and
// can be built from main at any time — including after the storage migration's
// Phase 1 removed aws-sdk-go-v2 (see design decision D6).
//
// The signing math is exercised against known-good vectors in sign_test.go.
// Those vectors were generated by an independent Python stdlib oracle
// (/tmp/sigv4_oracle.py at authoring time), not from memory, so agreement is a
// strong correctness signal rather than a circular self-check.
package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"sort"
	"strings"
)

// emptyStringSHA256 is the hex SHA-256 of the empty string, used as the
// x-amz-content-sha256 value for GET requests with no body. It is the
// well-known constant e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
var emptyStringSHA256 = sha256Hex(nil)

// sha256Hex returns the hex-encoded SHA-256 of data.
func sha256Hex(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// hmacSHA256 returns HMAC-SHA256(key, msg).
func hmacSHA256(key, msg []byte) []byte {
	h := hmac.New(sha256.New, key)
	h.Write(msg)
	return h.Sum(nil)
}

// deriveSigningKey computes the SigV4 signing key from the secret access key
// and the date/region/service scope.
func deriveSigningKey(secret, dateStamp, region, service string) []byte {
	kDate := hmacSHA256([]byte("AWS4"+secret), []byte(dateStamp))
	kRegion := hmacSHA256(kDate, []byte(region))
	kService := hmacSHA256(kRegion, []byte(service))
	return hmacSHA256(kService, []byte("aws4_request"))
}

// escapeS3Path percent-encodes a request path for use as the SigV4 canonical
// URI (and as the wire request path). Each path segment is encoded per the
// AWS spec — every byte except the unreserved set [A-Za-z0-9-._~] becomes %XX
// — while '/' separators are preserved. This mirrors Python's
// urllib.parse.quote(segment, safe="").
func escapeS3Path(p string) string {
	var b strings.Builder
	for _, r := range p {
		if r == '/' {
			b.WriteByte('/')
			continue
		}
		if isUnreserved(r) {
			b.WriteRune(r)
		} else {
			// Encode each UTF-8 byte of the rune.
			for _, byt := range []byte(string(r)) {
				fmt.Fprintf(&b, "%%%02X", byt)
			}
		}
	}
	return b.String()
}

// isUnreserved reports whether r is in the SigV4 unreserved set.
func isUnreserved(r rune) bool {
	switch {
	case r >= 'A' && r <= 'Z':
		return true
	case r >= 'a' && r <= 'z':
		return true
	case r >= '0' && r <= '9':
		return true
	case r == '-' || r == '.' || r == '_' || r == '~':
		return true
	}
	return false
}

// buildAuthorization computes the SigV4 Authorization header value for a
// request with no body (a GET). canonicalURIRaw is the raw request path
// (e.g. "/bucket/userid/uuid"); it is percent-encoded here to form the
// canonical URI. host is the Host header value (path-style requests use the
// endpoint host without a bucket prefix). extraHeaders are additional headers
// to include in the signed set (keys lowercased); the host, x-amz-date, and
// x-amz-content-sha256 headers are always signed.
func buildAuthorization(method, canonicalURIRaw, canonicalQuery, host, region, service, accessKey, secretKey, amzDate string, extraHeaders map[string]string) string {
	canonicalURI := escapeS3Path(canonicalURIRaw)

	headers := map[string]string{
		"host":                 host,
		"x-amz-content-sha256": emptyStringSHA256,
		"x-amz-date":           amzDate,
	}
	for k, v := range extraHeaders {
		headers[strings.ToLower(strings.TrimSpace(k))] = strings.TrimSpace(v)
	}

	signed := make([]string, 0, len(headers))
	for k := range headers {
		signed = append(signed, k)
	}
	sort.Strings(signed)

	var canonicalHeaders strings.Builder
	for _, h := range signed {
		canonicalHeaders.WriteString(h)
		canonicalHeaders.WriteByte(':')
		canonicalHeaders.WriteString(strings.TrimSpace(headers[h]))
		canonicalHeaders.WriteByte('\n')
	}

	canonicalRequest := strings.Join([]string{
		method,
		canonicalURI,
		canonicalQuery,
		canonicalHeaders.String(),
		strings.Join(signed, ";"),
		emptyStringSHA256,
	}, "\n")

	dateStamp := amzDate[:8]
	scope := strings.Join([]string{dateStamp, region, service, "aws4_request"}, "/")
	stringToSign := strings.Join([]string{
		"AWS4-HMAC-SHA256",
		amzDate,
		scope,
		sha256Hex([]byte(canonicalRequest)),
	}, "\n")

	sig := hmacSHA256(deriveSigningKey(secretKey, dateStamp, region, service), []byte(stringToSign))
	signature := hex.EncodeToString(sig)

	return fmt.Sprintf("AWS4-HMAC-SHA256 Credential=%s/%s, SignedHeaders=%s, Signature=%s",
		accessKey, scope, strings.Join(signed, ";"), signature)
}

// signGET signs an *http.Request for a path-style S3/B2 GET in place, setting
// the x-amz-date, x-amz-content-sha256, Host, and Authorization headers. The
// request URL must already carry the percent-encoded path (use escapeS3Path)
// so the bytes on the wire match the canonical request.
func signGET(req *http.Request, region, accessKey, secretKey, amzDate string) {
	req.Header.Set("x-amz-content-sha256", emptyStringSHA256)
	req.Header.Set("x-amz-date", amzDate)
	if req.Host == "" {
		req.Host = req.URL.Host
	}
	auth := buildAuthorization(req.Method, req.URL.EscapedPath(), "", req.Host,
		region, "s3", accessKey, secretKey, amzDate, nil)
	req.Header.Set("Authorization", auth)
}
