package main

import (
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"regexp"
	"testing"
)

// oracleVector is a known-good SigV4 case generated by an independent Python
// stdlib implementation (hmac/hashlib/urllib), NOT by this Go code. Agreement
// on the full Authorization string — including the 64-hex signature — is a
// strong correctness signal: it validates the canonical-request construction,
// the string-to-sign, the signing-key derivation chain, and the percent
// encoding of the path, all against an independent reference.
type oracleVector struct {
	label        string
	method       string
	uriRaw       string
	host         string
	region       string
	service      string
	accessKey    string
	secretKey    string
	amzDate      string
	extra        map[string]string
	expectedAuth string
}

func TestBuildAuthorizationOracleVectors(t *testing.T) {
	cases := []oracleVector{
		{
			label:        "b2-get-file (realistic key + decommissioned dev creds)",
			method:       "GET",
			uriRaw:       "/zettelgarden-files-prod/42/abc-uuid",
			host:         "s3.us-east-005.backblazeb2.com",
			region:       "us-east-005",
			service:      "s3",
			accessKey:    "005aaa1f003b7270000000004",
			secretKey:    "K005MK6pAqC2wBJg4B90G7aTp4hNmNk",
			amzDate:      "20260729T120000Z",
			expectedAuth: "AWS4-HMAC-SHA256 Credential=005aaa1f003b7270000000004/20260729/us-east-005/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=65897063c474d290926a8fdbef32ca5dc562f5be85d7453c08a1e7765d4244e2",
		},
		{
			label:        "b2-get-thumb",
			method:       "GET",
			uriRaw:       "/zettelgarden-files-prod/42/abc-uuid_thumb.jpg",
			host:         "s3.us-east-005.backblazeb2.com",
			region:       "us-east-005",
			service:      "s3",
			accessKey:    "AKID",
			secretKey:    "supersecret",
			amzDate:      "20260101T000000Z",
			expectedAuth: "AWS4-HMAC-SHA256 Credential=AKID/20260101/us-east-005/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d16b6213ac6f1108b7908bdcfaf148d6aa565064a8be4f18fb43071d77b4ea3e",
		},
		{
			label:        "nested-deep-key",
			method:       "GET",
			uriRaw:       "/my-bucket/7/aaa/bbb/deep-key",
			host:         "s3.us-east-005.backblazeb2.com",
			region:       "us-east-005",
			service:      "s3",
			accessKey:    "AKIDEXAMPLE",
			secretKey:    "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY",
			amzDate:      "20260729T093042Z",
			expectedAuth: "AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20260729/us-east-005/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=d337507d7a04f3b2f0051b4e1c4632fea3b6234ec0038b2af9c86f581a681e36",
		},
		{
			label:        "with-special-segment (space + @ encoded, / preserved)",
			method:       "GET",
			uriRaw:       "/buc/k 1/file@name.txt",
			host:         "s3.us-east-005.backblazeb2.com",
			region:       "us-east-005",
			service:      "s3",
			accessKey:    "AKID",
			secretKey:    "secret",
			amzDate:      "20260729T093042Z",
			expectedAuth: "AWS4-HMAC-SHA256 Credential=AKID/20260729/us-east-005/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=5055e656573ea793261ad232966e689a0e471f353e88f5994104845fa206c361",
		},
	}
	for _, c := range cases {
		t.Run(c.label, func(t *testing.T) {
			got := buildAuthorization(c.method, c.uriRaw, "", c.host, c.region, c.service,
				c.accessKey, c.secretKey, c.amzDate, c.extra)
			if got != c.expectedAuth {
				t.Errorf("buildAuthorization mismatch\n  got:  %s\n  want: %s", got, c.expectedAuth)
			}
		})
	}
}

// TestEscapeS3Path pins the percent-encoding contract: '/' preserved, space and
// '@' encoded, unreserved chars passed through. (This is what the
// with-special-segment oracle vector relies on, asserted in isolation here.)
func TestEscapeS3Path(t *testing.T) {
	cases := map[string]string{
		"/buc/k 1/file@name.txt":   "/buc/k%201/file%40name.txt",
		"/bucket/42/abc-uuid":      "/bucket/42/abc-uuid",
		"/bucket/42/abc_thumb.jpg": "/bucket/42/abc_thumb.jpg",
	}
	for in, want := range cases {
		if got := escapeS3Path(in); got != want {
			t.Errorf("escapeS3Path(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestSignGETRoundTrip confirms signGET wires its arguments into buildAuthorization
// correctly (host from URL, escaped path) and that the resulting request is
// sendable with a streaming body. The server re-derives the expected Authorization
// from the received request and compares.
func TestSignGETRoundTrip(t *testing.T) {
	const body = "the quick brown file"
	var seenAuth string
	var seenPath string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		seenAuth = r.Header.Get("Authorization")
		seenPath = r.URL.EscapedPath()
		w.Header().Set("Content-Type", "application/octet-stream")
		_, _ = io.WriteString(w, body)
	}))
	defer srv.Close()

	// Build the request path-style, matching how the migration tool does it.
	bucket := "zettelgarden-files-prod"
	key := "42/round-trip-uuid"
	escapedPath := escapeS3Path("/" + bucket + "/" + key)
	rawURL := srv.URL + escapedPath
	req, err := http.NewRequest(http.MethodGet, rawURL, nil)
	if err != nil {
		t.Fatalf("NewRequest: %v", err)
	}
	const amzDate = "20260729T120000Z"
	signGET(req, "us-east-005", "AKID", "secret", amzDate)

	// The host the request was signed with must be the test server's host.
	wantAuth := buildAuthorization(http.MethodGet, escapedPath, "", req.Host,
		"us-east-005", "s3", "AKID", "secret", amzDate, nil)

	resp, err := http.DefaultClient.Do(req.WithContext(context.Background()))
	if err != nil {
		t.Fatalf("Do: %v", err)
	}
	defer resp.Body.Close()
	got, _ := io.ReadAll(resp.Body)
	if string(got) != body {
		t.Errorf("body = %q, want %q", got, body)
	}

	// Now that the handler has run, the server-side captures must match.
	if seenAuth != wantAuth {
		t.Errorf("server saw Authorization %q, want %q", seenAuth, wantAuth)
	}
	if seenPath != escapedPath {
		t.Errorf("server saw path %q, want %q", seenPath, escapedPath)
	}

	// Sanity: the Authorization header is well-formed.
	if !regexp.MustCompile(`^AWS4-HMAC-SHA256 Credential=AKID/20260729/us-east-005/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=[0-9a-f]{64}$`).
		MatchString(seenAuth) {
		t.Errorf("Authorization header malformed: %q", seenAuth)
	}
}
